#PBS -N fep
#PBS -q fep
#PBS -l nodes=1:ppn=1:gpus=1
#PBS -S /bin/bash
#PBS -j oe

date
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
export LD_LIBRARY_PATH=/public/software/lib/:$LD_LIBRARY_PATH
source /public/software/compiler/intel/intel-compiler-2017.5.239/bin/compilervars.sh intel64
cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR

NAMD="/public/software/apps/NAMD_3.0alpha9/namd3 +p1 +devices 0"

for (( ii=1; ii<=2; ii++ )); do
    rsync -avh eq/fep.namd eq/fep.tcl eq/equilibrate.coor eq/equilibrate.vel eq/equilibrate.xsc t$ii
    $NAMD t$ii/fep.namd >& t$ii/LOG_fep
done